name: Preview (Pull Request)

on:
  pull_request:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11
          run_install: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: cp wrangler.preview.jsonc wrangler.jsonc

      - run: pnpm build

      - uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        id: deploy-workers-preview
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions upload --message "Deployed preview pages by GitHub Actions branch ${{ github.ref_name }}"

      - uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        if: >-
          ${{ steps.deploy-workers-preview.outcome == 'success' }}
        with:
          header: preview-deployment
          hide_and_recreate: true
          hide_classify: 'OUTDATED'
          message: |
            ## 🚀 Deploying ${{ github.event.repository.name }} with Cloudflare Workers
            <table>
              <tr>
                <th scope="row">Workers Preview URL</th>
                <td><a href="${{ steps.deploy-workers-preview.outputs.deployment-url }}" target="_blank" rel="noopener noreferrer">${{ steps.deploy-workers-preview.outputs.deployment-url }}</a></td>
              </tr>
            </table>
